import { Info } from 'lucide-react';
import { DemoNotice, PageHeader } from '../components/platform/PageHeader';
import { MetricCard, Panel } from '../components/platform/MetricCard';
import { demoActionDistribution, demoAnalyticsSummary, demoModalityDistribution, demoProcessedTrend, demoRiskDistribution } from '../data/demo/analytics';

function Bars({ points, color = 'bg-accent' }: { points: { label: string; value: number }[]; color?: string }) {
  const maximum = Math.max(...points.map((point) => point.value));
  return <div className="space-y-3">{points.map((point) => <div key={point.label}><div className="mb-1.5 flex justify-between text-xs"><span className="text-ink-muted">{point.label}</span><span className="font-mono font-semibold text-ink">{point.value}%</span></div><div className="h-2 overflow-hidden rounded-full bg-raised"><div className={`h-full rounded-full ${color}`} style={{ width: `${point.value / maximum * 100}%` }} /></div></div>)}</div>;
}

export function Analytics() {
  return <div className="mx-auto max-w-[1600px]"><PageHeader eyebrow="Decision intelligence" title="Moderation analytics" description="A readable foundation for volume, risk, modality, and review performance analysis." /><DemoNotice>Demo analytics · sample distributions only · no production telemetry connected</DemoNotice><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{demoAnalyticsSummary.map((metric) => <MetricCard key={metric.label} metric={metric} />)}</div><div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-[minmax(0,1.3fr)_minmax(320px,0.7fr)]"><Panel title="Content processed" eyebrow="Seven-day demo trend"><div className="flex h-52 items-end gap-3 border-b border-line px-2 pb-0 pt-6">{demoProcessedTrend.map((point) => <div key={point.label} className="flex min-w-0 flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-md bg-accent/80 transition-colors hover:bg-accent" style={{ height: `${point.value / 84 * 100}%` }} title={`${point.value} demo items`} /><span className="text-[10px] text-ink-faint">{point.label}</span></div>)}</div></Panel><Panel title="Risk distribution" eyebrow="Demo content mix"><Bars points={demoRiskDistribution} color="bg-moderate" /></Panel></div><div className="mt-4 grid grid-cols-1 gap-4 lg:grid-cols-2"><Panel title="Modality distribution" eyebrow="Primary trigger share"><Bars points={demoModalityDistribution} color="bg-accent" /></Panel><Panel title="Moderation actions" eyebrow="Demo policy outcomes"><Bars points={demoActionDistribution} color="bg-high" /></Panel></div><p className="mt-4 flex items-center gap-2 text-[11px] text-ink-faint"><Info className="h-3.5 w-3.5" aria-hidden="true" />These charts are presentation scaffolding for a future analytics service.</p></div>;
}
