import { Activity, CheckCircle2, Clock3, Info, ShieldAlert } from 'lucide-react';
import { DemoNotice, PageHeader } from '../components/platform/PageHeader';
import { Panel } from '../components/platform/MetricCard';

const health = [
  { label: 'Vision model', value: 'Demo healthy', detail: 'No live endpoint connected', tone: 'text-low' },
  { label: 'Audio model', value: 'Demo evaluating', detail: 'Evaluation placeholder', tone: 'text-moderate' },
  { label: 'Text model', value: 'Demo healthy', detail: 'No live endpoint connected', tone: 'text-low' }
];

const metrics = [
  ['Inference latency', '184 ms', 'Demo target'], ['Precision', '0.93', 'Evaluation placeholder'], ['Recall', '0.88', 'Evaluation placeholder'], ['F1 score', '0.90', 'Evaluation placeholder'], ['ROC-AUC', '0.95', 'Evaluation placeholder'], ['Drift status', 'Not connected', 'No monitoring source']
];

export function MLOps() {
  return <div className="mx-auto max-w-[1600px]"><PageHeader eyebrow="Model operations" title="MLOps monitoring" description="A monitoring surface for model health, quality, and deployment context once real services are connected." /><DemoNotice>Mock monitoring values · intentionally unconnected to model infrastructure</DemoNotice><div className="grid grid-cols-1 gap-4 lg:grid-cols-3">{health.map((item) => <article key={item.label} className="rounded-xl border border-line bg-surface p-4 shadow-card"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-ink-muted">{item.label}</p><p className={`mt-2 text-sm font-semibold ${item.tone}`}>{item.value}</p></div><Activity className="h-4 w-4 text-ink-faint" aria-hidden="true" /></div><p className="mt-3 text-[11px] text-ink-faint">{item.detail}</p></article>)}</div><div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(320px,0.8fr)]"><Panel title="Evaluation snapshot" eyebrow="Placeholder metrics"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{metrics.map(([label, value, detail]) => <div key={label} className="rounded-lg border border-line bg-panel p-3"><p className="text-[11px] text-ink-muted">{label}</p><p className="mt-2 font-mono text-lg font-semibold text-ink">{value}</p><p className="mt-1 text-[10px] text-ink-faint">{detail}</p></div>)}</div></Panel><Panel title="Deployment timeline" eyebrow="No connected infrastructure"><div className="space-y-4"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-low" aria-hidden="true" /><div><p className="text-xs font-semibold text-ink">Last demo training</p><p className="mt-0.5 text-[11px] text-ink-faint">Sep 18, 2026 · sample metadata</p></div></div><div className="flex gap-3"><Clock3 className="mt-0.5 h-4 w-4 shrink-0 text-moderate" aria-hidden="true" /><div><p className="text-xs font-semibold text-ink">Last demo deployment</p><p className="mt-0.5 text-[11px] text-ink-faint">Not connected to a runtime</p></div></div><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-ink-faint" aria-hidden="true" /><div><p className="text-xs font-semibold text-ink">Drift monitoring</p><p className="mt-0.5 text-[11px] text-ink-faint">Awaiting a telemetry source</p></div></div></div></Panel></div><p className="mt-4 flex items-center gap-2 text-[11px] text-ink-faint"><Info className="h-3.5 w-3.5" aria-hidden="true" />No real model health, latency, quality, or drift claims are made by this page.</p></div>;
}
